### ISSUE TITLE
After proguard, compilation passed, but an IllegalStateException reported when init

### ISSUE THREAD

**Issue by DMingOu** [MikaelZero/mojito#45]
I init  `mojito` in my custom Application，so  the IllegalStateException came when the app started
```
Caused by: java.lang.IllegalStateException: OkHttpClient::class.java.`package` must not be null
  at sW1.<clinit>(AndroidLog.kt:3)
  at pW1.<clinit>(Platform.kt:2) 
  at WT1.<init>(OkHttpClient.kt:73) 
```
And I guess the reason is that `mojito-1.1.0` relies on a version of okhttp package with this bug--`Okhttp3   4.7.2`
I solved this problem by relying on the new fixed version--`Okhttp3   4.8.1`

Here is my solution code：
```
    //Glide
    implementation ('com.github.bumptech.glide:glide:4.11.0')
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
    implementation ('com.github.bumptech.glide:okhttp3-integration:4.11.0'){
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
    //mojito
    implementation 'net.mikaelzero.mojito:core:1.1.0'
    implementation 'net.mikaelzero.mojito:SketchImageFactory:1.1.0'
    implementation ('net.mikaelzero.mojito:GlideImageLoader:1.1.0'){
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
        exclude group: 'com.github.bumptech.glide', module: 'okhttp3-integration'
    }
     //Okhttp3
    implementation("com.squareup.okhttp3:okhttp:4.8.1")
```

**Comment by MikaelZero** [comment]
try new version V1.5
